version: 2
jobs:
  build_selenium:
    docker:
      - image: circleci/node:10.16-browsers
      - image: selenium/standalone-chrome:3.141.59-yttrium
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
     
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      - run:
          name: create docker network
          command: docker network create grid
     
      - run:
          name: install selenium-hub
          command: docker run -d --rm -p 4444:4444 --net grid --name selenium-hub selenium/hub:3.141.59-yttrium
          
      - run:
          name: install selenium-node
          command: docker run -d --rm --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-chrome:3.141.59-yttrium
      
      - run:
          name: install-npm
          command: npm install
        
      # run tests!
      - run: 
          name: run selenium auto tests
          command: npm run test:local

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_selenium:
          filters:
            branches:
              only: master
